#!/bin/bash

rustup install nightly-2024-01-11
rustup component add rustfmt --toolchain nightly-2024-01-11
cargo +nightly-2024-01-11 fmt --all -- --config format_code_in_doc_comments=true

buildargs=(
    "-p smartvaults-core"
    "-p smartvaults-core --features reserves"
    "-p smartvaults-protocol"
    "-p smartvaults-sdk"
    "-p smartvaults-cli"
    "-p smartvaults-desktop"
    "-p smartvaults-sdk-ffi"
)

for arg in "${buildargs[@]}"; do
    echo  "Running with '$arg' arg"
    cargo test $arg
    cargo clippy $arg
    echo
done

buildargs=(
    "-p smartvaults-core --target wasm32-unknown-unknown"
    "-p smartvaults-protocol --target wasm32-unknown-unknown"
    "-p smartvaults-core-js --target wasm32-unknown-unknown"
)

for arg in "${buildargs[@]}"; do
    echo  "Running with '$arg' arg"
    cargo clippy $arg
    echo
done
