#!/bin/bash

cargo fmt --all -- --config format_code_in_doc_comments=true

buildargs=(
    "-p coinstr-core"
    "-p coinstr-core --features hwi"
    "-p coinstr-sdk"
    "-p coinstr-sdk --features hwi"
    "-p coinstr-cli"
    "-p coinstr"
    "-p coinstr-ffi"
)

for arg in "${buildargs[@]}"; do
    echo  "Running with '$arg' arg"
    cargo test $arg
    cargo clippy $arg
    echo
done
