@startuml

package "SmartVaults" {
  [SmartVaults Web \n(Policy Builder)]
  [SmartVaults CLI] 
  [SmartVaults GUI]
}

cloud "Bitcoin Network"

database "Events" 
[SmartVaults Web \n(Policy Builder)] <--> [Nostr Relay]

[Nostr Relay] <--> Events
[SmartVaults CLI] <--> "Bitcoin Network"
[SmartVaults GUI] <--> "Bitcoin Network"

[SmartVaults CLI] <--> [Nostr Relay]
[SmartVaults GUI] <--> [Nostr Relay]

note left of [Nostr Relay]
 Default 
 implementation 
end note

note right of [Events]
 Custom event KINDS for policies, 
 proposals, and PSBTs 
end note

@enduml